name: Deploy static content to Pages

on:
  # هيشتغل تلقائي لما تعملي Push على الـ main
  push:
    branches: ["main"]
  # بيسمحلك تشغلي الـ Workflow يدوياً من تاب Actions
  workflow_dispatch:

# إعطاء الصلاحيات اللازمة للرفع
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        # هنا استخدمنا أحدث إصدار v3 عشان نحل مشكلة السيرفر
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
